version: '3'

services:
  db:
    image: my_mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    expose:
      - "3306"
    volumes:
      - ./requirements/mariadb/tools/db_volumes:/var/lib/mysql

  wp:
    depends_on:
      - db
    image: my_wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    expose:
      - "9000"
    volumes:
      - ./requirements/wordpress/tools/wp_volumes:/var/www/html

  ng:
    depends_on:
      - wp
    image: my_nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/wordpress/tools/wp_volumes:/var/www/html

volumes:
  db_volumes:
  wp_volumes:
