version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    expose:
      - "3306"
    volumes:
      - type: volume
        source: db_volume
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /home/minskim2/data/mariadb
        target: /var/lib/mysql
    networks:
      - intra

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file: .env
    expose:
      - "9000"
    volumes:
      - type: volume
        source: wp_volume
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /home/minskim2/data/wordpress
        target: /var/www/html
    networks:
      - intra

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - type: volume
        source: wp_volume
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /home/minskim2/data/wordpress
        target: /var/www/html
    networks:
      - intra

volumes:
  db_volume:
  wp_volume:

networks:
  intra:
    driver: bridge
