version: '3'

services:
  db:
    image: my_mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    expose:
      - "3306"
    volumes:
      - /home/minskim2/data/db_volumes:/var/lib/mysql
    networks:
      - intra

  wp:
    depends_on:
      - db
    image: my_wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    expose:
      - "9000"
    volumes:
      - /home/minskim2/data/wp_volumes:/var/www/html
    networks:
      - intra

  ng:
    depends_on:
      - wp
    image: my_nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - /home/minskim2/data/wp_volumes:/var/www/html
    networks:
      - intra

volumes:
  db_volumes:
  wp_volumes:

networks:
  intra:
    driver: bridge
