version: '3'

services:
  nestjs:
    container_name: nestjs
    build: ./requirements/nestjs
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: nestjs_volume
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ~/ft_transcendence
        target: /ft_transcendence
    networks:
      - intra

volumes:
  nestjs_volume:

networks:
  intra:
    driver: bridge
